"use client";
import { Suspense,useEffect,useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { ProductShell } from './product-shell';
import { liveApi,type LiveRun,type RunSummary } from '@/lib/live-types';
export function LiveProductPage(){return <Suspense fallback={<ProductShell><p className="recovered-muted" role="status">Loading products…</p></ProductShell>}><LiveProductContent/></Suspense>}
function LiveProductContent(){
 const search=useSearchParams().toString();
 const [run,setRun]=useState<LiveRun|null>(null),[runs,setRuns]=useState<RunSummary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[paid,setPaid]=useState(false),[busy,setBusy]=useState(false),[cancelled,setCancelled]=useState(false);
 useEffect(()=>{let alive=true;const controller=new AbortController();async function load(){try{const params=new URLSearchParams(search),id=params.get('run');setCancelled(params.has('cancelled'));if(id){const data=await liveApi<LiveRun>(`/api/runs/${encodeURIComponent(id)}`,{signal:controller.signal});if(!alive)return;setRun(data);if(data.product){const session=params.get('session_id');const result=await liveApi<{entitled:boolean}>(`/api/runs/${id}/${session?'payment?session_id='+encodeURIComponent(session):'access'}`,{signal:controller.signal});if(alive)setPaid(result.entitled);}}else{const list=await liveApi<{runs:RunSummary[]}>('/api/runs',{signal:controller.signal});if(alive)setRuns(list.runs);}}catch(e){if(alive)setError(e instanceof Error?e.message:'Could not load products')}finally{if(alive)setLoading(false)}}void load();return()=>{alive=false;controller.abort()}},[search]);
 async function checkout(){if(!run)return;setBusy(true);setError('');try{const data=await liveApi<{url:string;entitled?:boolean}>(`/api/runs/${run.id}/checkout`,{method:'POST'});if(data.entitled){setPaid(true);setBusy(false);return}const url=new URL(data.url);if(url.origin!=='https://checkout.stripe.com')throw Error('Invalid checkout URL');location.assign(url.href)}catch(e){setError(e instanceof Error?e.message:'Checkout unavailable');setBusy(false)}}
 const product=run?.product;
 return <ProductShell><section className="recovered-hero"><p className="service-kicker">{product?'RECOVERED SOFTWARE / LIVE PREVIEW':'THE AFTERLIFE PORTFOLIO'}</p><h1>{product?.name||'Useful software.'}<br/><span>{product?'A second chance.':'A new beginning.'}</span></h1><p>{product?.description||'Products discovered, recovered and packaged by the Afterlife agents. Every product starts with a real open-source repository.'}</p></section>
 {error&&<p className="recovered-error" role="alert">{error} <button className="quiet-button" onClick={()=>location.reload()}>Retry ↻</button></p>}
 {loading?<p role="status" className="recovered-muted">Checking the live portfolio…</p>:product?<>
 <section className="recovered-grid"><article className="recovered-card"><p className="service-kicker">PRODUCT LIVE</p><h2 style={{marginTop:12}}>{product.capability}</h2><p className="recovered-muted">Use the temporary preview now. It runs the recovered repository’s actual code.</p><a className="recovered-primary" href={product.url} target="_blank" rel="noopener noreferrer">Open {product.name} ↗</a><p className="recovered-fine">Hosted in a Brainbase sandbox. This temporary URL may stop when the sandbox expires.</p></article>
 <article className="recovered-card"><p className="service-kicker">MONETIZATION / STRIPE TEST MODE</p><h2 style={{marginTop:12}}>{paid?'Payment verified':`Test checkout · $${(product.priceCents/100).toFixed(2)}`}</h2><p className="recovered-muted">{paid?'Stripe confirmed the payment and saved your access for this product.':'The preview is free during the hackathon. Try the product’s payment flow with a Stripe test card; no real money is charged.'}</p>{!paid&&<button disabled={busy||!run?.billing?.configured} onClick={()=>void checkout()} className="recovered-primary">{busy?'Opening Stripe…':'Try test checkout ↗'}</button>}{cancelled&&!paid&&<p className="recovered-fine">Checkout cancelled. You can still use the free preview.</p>}<p className="recovered-fine">Test card: 4242 4242 4242 4242 · any future expiry · any CVC. Use the same browser when returning.</p></article></section>
 <section className="recovered-proof recovered-card"><div><p className="service-kicker">SOURCE & VERIFICATION</p><h2>Built from the original.</h2><p>{run?.repair?.summary}</p>{product.limitations.map((limit,i)=><p key={i}>{limit}</p>)}</div><dl><dt>Repository</dt><dd><a href={`https://github.com/${product.repository}`} target="_blank" rel="noopener noreferrer">{product.repository} ↗</a></dd><dt>Revision</dt><dd><code>{product.revision}</code></dd><dt>Run</dt><dd><Link href={`/afterlife/?run=${run?.id}`}>View agent activity ↗</Link></dd><dt>Billing</dt><dd>{paid?'Verified test payment':'Stripe test mode · free preview'}</dd></dl></section>
 </>:run?<section className="recovered-card"><h2>{run.state==='failed'?'This run stopped before launch.':run.state==='passed'?'No investment was made.':'This product is still being built.'}</h2><p className="recovered-muted">{run.error||run.decision?.reason||'The product appears after its temporary preview passes a health check.'}</p><Link className="recovered-primary" href={`/afterlife/?run=${run.id}`}>Watch the agents ↗</Link></section>:<section className="recovered-grid" style={{marginBottom:50}}>{runs.filter(r=>r.product).map(r=><article className="recovered-card" key={r.id}><p className="service-kicker">{r.state.toUpperCase()}</p><h2>{r.product!.name}</h2><p className="recovered-muted">{r.product!.description}</p><Link href={`/product/?run=${r.id}`} className="recovered-primary">Open product ↗</Link></article>)}{!runs.some(r=>r.product)&&<article className="recovered-card"><h2>No verified product yet.</h2><p className="recovered-muted">Follow the current run or describe a new opportunity in the console.</p><Link href="/afterlife/" className="recovered-primary">Open console ↗</Link></article>}</section>}
 </ProductShell>
}
