"use client";
import { Suspense,useEffect,useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { ProductShell } from './product-shell';
import { liveApi,type LiveRun,type RunSummary } from '@/lib/live-types';
export function LiveProductPage(){return <Suspense fallback={<ProductShell><p className="recovered-muted" role="status">Loading products…</p></ProductShell>}><LiveProductContent/></Suspense>}
function LiveProductContent(){
 const search=useSearchParams().toString();
 const [run,setRun]=useState<LiveRun|null>(null),[runs,setRuns]=useState<RunSummary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[paid,setPaid]=useState(false),[busy,setBusy]=useState(false),[cancelled,setCancelled]=useState(false);
 useEffect(()=>{let alive=true;const controller=new AbortController();async function load(){try{const params=new URLSearchParams(search),id=params.get('run');setCancelled(params.has('cancelled'));if(id){const data=await liveApi<LiveRun>(`/api/runs/${encodeURIComponent(id)}`,{signal:controller.signal});if(!alive)return;setRun(data);setPaid(false);setError('');if(data.product){const session=params.get('session_id');const result=await liveApi<{entitled:boolean}>(`/api/runs/${id}/${session?'payment?session_id='+encodeURIComponent(session):'access'}`,{signal:controller.signal});if(alive)setPaid(result.entitled);}}else{const list=await liveApi<{runs:RunSummary[]}>('/api/runs',{signal:controller.signal});if(alive){setRuns(list.runs);setRun(null);setPaid(false);setError('');}}}catch(e){if(alive)setError(e instanceof Error?e.message:'Could not load products')}finally{if(alive)setLoading(false)}}void load();return()=>{alive=false;controller.abort()}},[search]);
 async function checkout(){if(!run)return;setBusy(true);setError('');try{const data=await liveApi<{url:string;entitled?:boolean}>(`/api/runs/${run.id}/checkout`,{method:'POST'});if(data.entitled){setPaid(true);setBusy(false);return}const url=new URL(data.url);if(url.origin!=='https://checkout.stripe.com')throw Error('Invalid checkout URL');location.assign(url.href)}catch(e){setError(e instanceof Error?e.message:'Checkout unavailable');setBusy(false)}}
 const product=run?.product;
 return <ProductShell><section className="recovered-hero"><h1>{product?.name||'Products'}</h1>{product?.description&&<p>{product.description}</p>}</section>
 {error&&<p className="recovered-error" role="alert">{error} <button className="quiet-button" onClick={()=>location.reload()}>Retry ↻</button></p>}
 {loading?<p role="status" className="recovered-muted">Loading…</p>:product?<>
 <section className="recovered-grid"><article className="recovered-card"><p className="service-kicker">PRODUCT LIVE</p><h2 style={{marginTop:12,fontSize:20,lineHeight:1.3}}>Free preview</h2><p className="recovered-muted" style={{lineHeight:1.7,margin:"14px 0 20px"}}>{product.capability}</p><a className="recovered-primary" href={product.url} target="_blank" rel="noopener noreferrer">Open {product.name} ↗</a><p className="recovered-fine">Temporary URL</p></article>
 <article className="recovered-card"><p className="service-kicker">MONETIZATION / STRIPE TEST MODE</p><h2 style={{marginTop:12,fontSize:20,lineHeight:1.3}}>{paid?'Payment verified':`Test checkout · $${(product.priceCents/100).toFixed(2)}`}</h2><p className="recovered-muted">{paid?'Payment verified.':'Free preview · Stripe test mode'}</p>{!paid&&<button disabled={busy||!run?.billing?.configured} onClick={()=>void checkout()} className="recovered-primary">{busy?'Opening Stripe…':'Try test checkout ↗'}</button>}{cancelled&&!paid&&<p className="recovered-fine">Checkout cancelled.</p>}<p className="recovered-fine">Test card: 4242 4242 4242 4242 · any future expiry · any CVC.</p></article></section>
 <section className="recovered-proof recovered-card"><div><p className="service-kicker">SOURCE & VERIFICATION</p><h2>Source</h2><p>{run?.repair?.summary}</p>{product.limitations.map((limit,i)=><p key={i}>{limit}</p>)}</div><dl><dt>Repository</dt><dd><a href={`https://github.com/${product.repository}`} target="_blank" rel="noopener noreferrer">{product.repository} ↗</a></dd><dt>Revision</dt><dd><code>{product.revision}</code></dd><dt>Run</dt><dd><Link href={`/afterlife/?run=${run?.id}`}>View agent activity ↗</Link></dd><dt>Billing</dt><dd>{paid?'Verified test payment':'Stripe test mode · free preview'}</dd></dl></section>
 </>:run?<section className="recovered-card"><h2>{run.state==='failed'?'Run stopped.':run.state==='passed'?'No investment.':'Building…'}</h2><p className="recovered-muted">{run.error||run.decision?.reason||''}</p><Link className="recovered-primary" href={`/afterlife/?run=${run.id}`}>View run ↗</Link></section>:<section className="recovered-grid" style={{marginBottom:50}}>{runs.filter(r=>r.product).map(r=><article className="recovered-card" key={r.id}><p className="service-kicker">{r.state.toUpperCase()}</p><h2>{r.product!.name}</h2><p className="recovered-muted">{r.product!.description}</p><Link href={`/product/?run=${r.id}`} className="recovered-primary">Open product ↗</Link></article>)}{!runs.some(r=>r.product)&&<article className="recovered-card"><h2>No products yet.</h2><Link href="/afterlife/" className="recovered-primary">Open console ↗</Link></article>}</section>}
 </ProductShell>
}
