"use client";
import { useCallback, useEffect, useRef, useState, type ComponentType, type ChangeEvent, type KeyboardEvent, type MouseEvent } from 'react';
import { liveApi, type LiveRun, type RunSummary } from '@/lib/live-types';
import design from '@/designs/console-live.json';
import { useRouter } from 'next/navigation';
const colors = { text:'#EDEDED', muted:'#8F8F8F', brand:'#FF6B2C', ok:'#34D399', fail:'#FF5A5F', blue:'#52A8FF' };
export function LiveConsole() {
 const router=useRouter();
 const [View,setView]=useState<ComponentType<{values:Record<string,unknown>}>|null>(null);
 const [run,setRun]=useState<LiveRun|null>(null), [runs,setRuns]=useState<RunSummary[]>([]), [id,setId]=useState('');
 const [thesis,setThesis]=useState('');
 const hydratedRun=useRef(''),draftEdited=useRef(false);
 const [error,setError]=useState(''),[starting,setStarting]=useState(false),[connected,setConnected]=useState(false),[selected,setSelected]=useState(''),[rail,setRail]=useState('portfolio'),[cmd,setCmd]=useState(false),[query,setQuery]=useState(''),[cmdIndex,setCmdIndex]=useState(0);
 useEffect(()=> { let alive=true; import('@/vendor/design-runtime').then(({createDesignComponent})=> { if(alive)setView(()=>createDesignComponent('live-console',design)); }).catch(()=>setError('The console could not load. Reload the page.')); return()=>{alive=false}; },[]);
 const loadList=useCallback(async()=>{const data=await liveApi<{runs:RunSummary[]}>('/api/runs');setRuns(data.runs);setConnected(true);return data.runs;},[]);
 useEffect(()=>{let alive=true;void liveApi<{runs:RunSummary[]}>('/api/runs').then(data=>{if(!alive)return;setRuns(data.runs);setConnected(true);const requested=new URLSearchParams(location.search).get('run');setId(requested||data.runs[0]?.id||'');}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false};},[]);
 useEffect(()=>{if(!id)return;let alive=true;let timeout:ReturnType<typeof setTimeout>;const controller=new AbortController();async function poll(){try{const data=await liveApi<LiveRun>(`/api/runs/${id}`,{signal:controller.signal});if(alive){if(hydratedRun.current!==data.id){if(!draftEdited.current)setThesis(data.thesis);hydratedRun.current=data.id}setRun(data);setError(data.refreshError||'');setConnected(true);}}catch(e){if(alive)setError(e instanceof Error?e.message:'Refresh failed');}finally{if(alive)timeout=setTimeout(poll,6000);}}void poll();return()=>{alive=false;controller.abort();clearTimeout(timeout)};},[id]);
 useEffect(()=>{function key(e:globalThis.KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setCmd(v=>!v)}if(e.key==='Escape')setCmd(false)}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const busy=starting||run?.state==='running'||run?.state==='starting';
 async function start(){if(busy)return;setStarting(true);setError('');try{const next=await liveApi<{id:string}>('/api/runs',{method:'POST',body:JSON.stringify({thesis})});setRun(null);setId(next.id);history.replaceState(null,'',`?run=${next.id}`);await loadList();}catch(e){setError(e instanceof Error?e.message:'Could not start run');}finally{setStarting(false)}}
 function choose(next:string){hydratedRun.current='';draftEdited.current=false;setCmd(false);setRun(null);setId(next);history.replaceState(null,'',`?run=${next}`)}
 const stages=run?.stages||[],candidates=run?.candidates||[],decision=run?.decision,live=run?.state==='live',product=run?.product;
 const candidate=candidates.find(c=>c.repository===selected)||candidates.find(c=>c.repository===decision?.repository)||candidates[0];
 const pill=(repo:string)=>decision?.decision==='FUND'?(repo===decision.repository?'Invest':'Pass'):decision?.decision==='PASS_ALL'?'Pass':'Analyzing';
 const fg=(s:string)=>s==='Invest'?colors.blue:s==='Complete'?colors.ok:s==='Failed'?colors.fail:s==='Analyzing'||s==='In progress'?colors.brand:colors.muted;
 const milestones=['scout','investment','resurrection','product','deployment'].map((kind,i)=>{const stage=stages.find(s=>s.kind===kind);const status=kind==='deployment'?(live?'Complete':product?'In progress':'Pending'):stage?(stage.status==='success'&&stage.resultStatus!=='FAILED'?'Complete':['fail','need_more_info','idle','cancelled'].includes(stage.status)||(stage.status==='success'&&stage.resultStatus==='FAILED')?'Failed':'In progress'):'Pending';return{label:['Discover repositories','Choose the investment','Recover and verify','Generate the product','Deploy and monetize'][i],detail:kind==='deployment'?(live?'Temporary URL verified · Stripe test checkout': 'Pending'):stage?.label||['Scout','Investment manager','Resurrection engineer','Product engineer'][i],status,dot:status==='In progress'?'● ':'',fg:fg(status),glyph:status==='Complete'?'✓':status==='Failed'?'×':String(i+1),labelColor:status==='Pending'?colors.muted:colors.text,border:status==='Pending'?'#333':fg(status),bg:status==='Complete'?'rgba(52,211,153,.1)':'transparent'};});
 const done=milestones.filter(m=>m.status==='Complete').length;
 const openProduct=()=>{if(product)router.push(`/product/?run=${run!.id}`);else router.push('/product/')};
 const commands=[{label:'Start discovery',group:'Run',run:()=>{setCmd(false);void start()}},{label:'Browse products',group:'Navigate',run:()=>router.push('/product/')},...runs.map(r=>({label:`${r.product?.name||r.thesis.slice(0,65)} · ${r.state}`,group:'Recent run',run:()=>choose(r.id)}))].filter(c=>(c.label+' '+c.group).toLowerCase().includes(query.toLowerCase()));
 const elapsed=run?Math.max(0,(run.updatedAt||run.createdAt)-run.createdAt):0;
 const values={
 isPortfolio:true,isPocket:false,checkoutOpen:false,panelTitle:rail==='portfolio'?'Portfolio':'Products',isRailPortfolio:rail==='portfolio',isRailProducts:rail==='products',railPortfolio:()=>setRail('portfolio'),railProducts:()=>{setRail('products');void loadList().catch(e=>setError(e.message))},railPortBg:rail==='portfolio'?'#1A1A1A':'transparent',railPortColor:colors.text,railProdBg:rail==='products'?'#1A1A1A':'transparent',railProdColor:colors.text,railNone:'transparent',railIdle:colors.muted,
 thesis,thesisInput:(e:ChangeEvent<HTMLTextAreaElement>)=>{draftEdited.current=true;setThesis(e.target.value)},connectionNote:connected?'Connected to Brainbase · public demo: one active run at a time':'Connecting to live service',runIdLabel:id?id.slice(0,8):'no run',productName:product?.name||'Products',productDescription:product?`${product.repository} · temporary free preview · Stripe test mode`:'No products yet.',liveLabel:live?'Live':busy?'Building':'Not launched',liveColor:live?colors.ok:colors.muted,
 pipePct:`${done/5*100}%`,progressPct:`${done/5*100}%`,progressColor:colors.brand,pipelineSummary:`${done} of 5 complete`,milestones,
 evaluate:()=>void start(),retry:()=>{if(error&&!run?.error){setError('');void loadList().then(list=>{if(!id&&list[0])choose(list[0].id)}).catch(e=>setError(e.message))}else void start()},runBtnLabel:starting?'Starting…':busy?'Running…':run?'New run':'Discover',runBtnCursor:busy?'default':'pointer',runBtnOpacity:busy?.55:1,isFailed:Boolean(error||run?.error||run?.state==='passed'),errorTitle:run?.state==='passed'?'No investment made':run?.state==='failed'?'Run stopped':'Service update',errorBody:error||run?.error||decision?.reason,isLive:live,openPocket:openProduct,
 stats:[{label:'Candidates',value:String(candidates.length),sub:candidates.length?'Discovered':'Pending',color:colors.text},{label:'Investment',value:decision?.decision==='FUND'?'1':'0',sub:decision?.repository||'No repository selected',color:colors.text},{label:'Products live',value:live?'1':'0',sub:product?.name||'Pending',color:live?colors.ok:colors.text},{label:'Elapsed',value:`${Math.floor(elapsed/60)}m ${elapsed%60}s`,sub:run?.state||'Ready',color:colors.text}],
 candSummary:candidates.length?`${candidates.length} discovered`:'Pending',noCandidates:!candidates.length,candidateEmpty:busy?'Discovering…':'No candidates yet.',candidates:candidates.map(c=>({dot:'',repo:c.repository,blurb:c.capability.slice(0,100),status:pill(c.repository),fg:fg(pill(c.repository)),bg:'#202020',decided:decision?'✓':'—',rowBg:c.repository===candidate?.repository?'#18181A':'transparent',rowShadow:c.repository===candidate?.repository?'inset 2px 0 0 #EDEDED':'none',onClick:()=>setSelected(c.repository)})),
 report:{dot:decision?'':'',repo:candidate?.repository||'Awaiting Scout',status:candidate?pill(candidate.repository):'Pending',fg:candidate?fg(pill(candidate.repository)):colors.muted,bg:'#202020',hasDecision:Boolean(decision),verdict:decision&&candidate&&decision.repository===candidate.repository?'Invest.':'Pass.',decision:decision&&candidate&&decision.repository===candidate.repository?decision.reason:candidate?.recommendation,sections:candidate?[{k:'Capability',v:candidate.capability},{k:'Product opportunity',v:candidate.productHypothesis},{k:'License',v:candidate.license},{k:'Maintenance context',v:candidate.evidence},{k:'Risks',v:candidate.risks},...(run?.repair&&candidate&&candidate.repository===decision?.repository?[{k:'Recovery',v:run.repair.summary}]:[])]:[{k:'Your thesis',v:run?.thesis||thesis}]},
 events:(run?.events||[]).map(e=>({time:new Date(e.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),text:e.text,color:e.status==='success'?colors.ok:colors.brand,textColor:colors.text})),noEvents:!run?.events?.length,eventCount:`${run?.events?.length||0} updates`,integrations:[{name:'Brainbase',role:'',status:connected?'Connected':'Checking'},{name:'Cloudflare',role:'',status:connected?'Live':'Checking'},{name:'Stripe',role:'',status:run?.billing?.configured?'Test mode':'Checking'}],
 cmdOpen:cmd,cmdQuery:query,cmdEmpty:!commands.length,openCmd:()=>{setCmd(true);setQuery('');setCmdIndex(0);void loadList().catch(e=>setError(e.message))},closeCmd:()=>setCmd(false),stop:(e:MouseEvent)=>e.stopPropagation(),cmdInput:(e:ChangeEvent<HTMLInputElement>)=>{setQuery(e.target.value);setCmdIndex(0)},cmdKey:(e:KeyboardEvent)=>{if(e.key==='ArrowDown'){e.preventDefault();setCmdIndex(i=>Math.min(i+1,commands.length-1))}if(e.key==='ArrowUp'){e.preventDefault();setCmdIndex(i=>Math.max(0,i-1))}if(e.key==='Enter')commands[cmdIndex]?.run()},cmdItems:commands.map((c,i)=>({...c,hover:()=>setCmdIndex(i),bg:i===cmdIndex?'#202020':'transparent',color:colors.text})),
 };
 if(!View)return <main className="design-loading" role="status">{error||'Loading Afterlife…'}</main>;
 return <div className="design-export"><View values={values}/></div>;
}
